# Firecrawl

networks:
  default:
    name: ${LLEMONSTACK_NETWORK_NAME}
    external: true

x-common-service: &common-service
  build:
    context: ${LLEMONSTACK_REPOS_PATH:-.}/firecrawl/apps/api
  image: firecrawl-api:latest

  ulimits:
    nofile:
      soft: 65535
      hard: 65535

  # Enable access to host if using Ollama
  # extra_hosts:
  #   - "host.docker.internal:host-gateway"

x-common-env: &common-env
  REDIS_URL: ${REDIS_URL:-redis://:${REDIS_PASSWORD}@redis:6379}
  REDIS_RATE_LIMIT_URL: ${REDIS_URL:-redis://:${REDIS_PASSWORD}@redis:6379}

  PLAYWRIGHT_MICROSERVICE_URL: ${PLAYWRIGHT_MICROSERVICE_URL:-http://firecrawl-playwright-service:3000/scrape}

  USE_DB_AUTHENTICATION: ${USE_DB_AUTHENTICATION:-false}

  OPENAI_API_KEY: ${OPENAI_API_KEY:-}
  OPENAI_BASE_URL: ${OPENAI_BASE_URL:-}
  MODEL_NAME: ${MODEL_NAME:-}
  MODEL_EMBEDDING_NAME: ${MODEL_EMBEDDING_NAME:-}
  OLLAMA_BASE_URL: ${OLLAMA_BASE_URL:-}

  SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL:-}

  BULL_AUTH_KEY: ${BULL_AUTH_KEY:-}
  TEST_API_KEY: ${TEST_API_KEY:-}

  SELF_HOSTED_WEBHOOK_URL: ${SELF_HOSTED_WEBHOOK_URL:-}

  SERPER_API_KEY: ${SERPER_API_KEY:-}
  SEARCHAPI_API_KEY: ${SEARCHAPI_API_KEY:-}

  LOGGING_LEVEL: ${LOGGING_LEVEL:-INFO}

  PROXY_SERVER: ${PROXY_SERVER:-}
  PROXY_USERNAME: ${PROXY_USERNAME:-}
  PROXY_PASSWORD: ${PROXY_PASSWORD:-}

  SEARXNG_ENDPOINT: ${SEARXNG_ENDPOINT:-}
  SEARXNG_ENGINES: ${SEARXNG_ENGINES:-}
  SEARXNG_CATEGORIES: ${SEARXNG_CATEGORIES:-}

  # POSTHOG_API_KEY: ${POSTHOG_API_KEY:-}
  # POSTHOG_HOST: ${POSTHOG_HOST:-}

  # SUPABASE_ANON_TOKEN: ${SUPABASE_ANON_TOKEN:-}
  # SUPABASE_URL: ${SUPABASE_URL:-}
  # SUPABASE_SERVICE_TOKEN: ${SUPABASE_SERVICE_TOKEN}

services:
  playwright-service:
    build:
      context: ${LLEMONSTACK_REPOS_PATH:-.}/firecrawl/apps/playwright-service-ts
    image: firecrawl-playwright-service:latest
    container_name: firecrawl-playwright-service
    environment:
      PORT: 3000
      PROXY_SERVER: ${PROXY_SERVER:-}
      PROXY_USERNAME: ${PROXY_USERNAME:-}
      PROXY_PASSWORD: ${PROXY_PASSWORD:-}
      BLOCK_MEDIA: ${BLOCK_MEDIA:-}

  api:
    <<: *common-service
    container_name: firecrawl-api
    environment:
      <<: *common-env
      HOST: "0.0.0.0"
      PORT: ${INTERNAL_PORT:-3002}
      FLY_PROCESS_GROUP: app
    depends_on:
      - playwright-service
    ports:
      - "${PORT:-3002}:${INTERNAL_PORT:-3002}"
    command: ["pnpm", "run", "start:production"]

  worker:
    <<: *common-service
    container_name: firecrawl-worker
    environment:
      <<: *common-env
      FLY_PROCESS_GROUP: worker
    depends_on:
      - playwright-service
      - api
    command: ["pnpm", "run", "workers"]
